name: Build and Push Docker Image

on:
  push:
    branches:
      - ci-cd

permissions:
  contents: write
  packages: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/siva-828926/bad-court:${{ github.sha }}

      - name: Checkout the target repository
        uses: actions/checkout@v2
        with:
          repository: Siva-828926/prj-badminton-manifest
          token: ${{ secrets.PAT_TOKEN }}
          path: ./prj-badminton-manifest

      - name: Update image name in target repository
        run: |
          cd prj-badminton-manifest
          sed -i 's|image: ghcr.io/siva-828926/bad-court:[^ ]*|image: ghcr.io/siva-828926/bad-court:${{ github.sha }}|' deployment.yml

      - name: Commit and push changes to target repository
        run: |
          cd prj-badminton-manifest
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -b update-image-for-${{ github.sha }}
          git add .
          git commit -m "Update image to ghcr.io/siva-828926/bad-court:${{ github.sha }}"
          git push origin update-image-for-${{ github.sha }}
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}
          commit-message: Update image to ghcr.io/siva-828926/bad-court:${{ github.sha }}
          branch: update-image-for-${{ github.sha }}
          title: Update image to ghcr.io/siva-828926/bad-court:${{ github.sha }}
          body: This PR updates the image to ghcr.io/siva-828926/bad-court:${{ github.sha }}
          base: master